# This is a basic workflow to help you get started with Actions

name: armtemplateDeploy

on:
  workflow_dispatch:

jobs:
  armDeploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name : Azure Login
        uses : Azure/login@v1
        with : 
          cred : ${{ secrets.AZURECREDENTIALS  }}