# This is a basic workflow to help you get started with Actions

name: armtemplateDeploy

on:
  push:
    branches:
      - main 
  workflow_dispatch:

jobs:
  armDeploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name : Azure Login
        uses : Azure/login@v1
        with : 
          creds : ${{ secrets.AZURECREDENTIALS  }}

      - name: Deploy Azure Resource Group with ARM Template and GitHub Actions
        uses: Azure/arm-deploy@v1
        with: 
          scope: subscription
          subscriptionId: 3790f202-487d-446b-8808-4e287a18c713
          region: eastus
          template: ./armtemplates/resourcegroup.json
          deploymentName: rg-GitHubActions-1

      - name: Deploy Storage Account using ARM Template and GitHub Actions
        uses: Azure/arm-deploy@v1
        with: 
          scope: resourcegroup
          resourceGroupName: rg-GitHubActions1
          subscriptionId: 3790f202-487d-446b-8808-4e287a18c713
          template: ./armtemplates/storageaccount.json
          parameters: ./armtemplates/storageaccount.parameters.json
          deploymentMode: incremental

