# This is a basic workflow to help you get started with Actions

name: armtemplateDeploy

on:
  push:
    branches:
      - main 
  workflow_dispatch:

jobs:
  armDeploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name : Azure Login
        uses : Azure/login@v1
        with : 
          creds : ${{ secrets.AZURECREDENTIALS  }}
