name: armtemplateDeploy

on:
  push:
    branches:
      - main 
  workflow_dispatch:

jobs:
  armDeploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name : Azure Login
        uses : Azure/login@v1
        with : 
          creds : ${{ secrets.AZURECREDENTIALS  }}

      - name: Deploy RG rg-GitHubActions using ARM Template GitHub Actions
        uses: Azure/arm-deploy@v1
        with: 
          scope: subscription
          subscriptionID: 3790f202-487d-446b-8808-4e287a18c713
          region: eastus
          template: ./armtemplates/resourcegroup.json
          deploymentName: rg-GitHubActions

      - name: Deploy storage account using ARM Template GitHub Actions
        uses: Azure/arm-deploy@v1
        id: storageAccountDeploy
        with: 
          scope: resourcegroup
          resourceGroupName: rg-GitHubActions
          subscriptionID: 3790f202-487d-446b-8808-4e287a18c713
          template: ./armtemplates/storageaccount.json
          parameters:
            ./armtemplates/storageaccount.parameters.json
            storageAccountName="hikumastore1"
            location="eastus2"
          deploymentMode: incremental

      - name: Deploy Virtual Machine
        uses: Azure/arm-deploy@v1
        with: 
          scope: resourcegroup
          resourceGroupName: rg-GitHubActions
          subscriptionID: 3790f202-487d-446b-8808-4e287a18c713
          template: ./armtemplates/virtualmachine.json
          parameters:
            adminPassword=${{ secrets.ubuntuVmPassword}}
          deploymentMode: incremental

